# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fb0eb60941e0e7bb38a2ca344b3bd123"
name = "esim_fulfillment"
application_url = "https://esim-api-production-a56a.up.railway.app"
embedded = false

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhook/orders/paid"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
